import { useEffect,useMemo,useState } from 'react';
import { Search,MapPin,SlidersHorizontal,X,ChevronRight,Heart,Maximize2,BedDouble,Bath,Map,LayoutGrid,ArrowUpRight,Check,Plus,Navigation,Building2 } from 'lucide-react';
import { useEstate } from './context';
import { api } from './api';
import { tr,locale } from './localization';
import { money,type Property } from './types';
import { Button,Empty,PropertyImage,AssignedAgentCard } from './ui';
import { PropertyMap,hasCoordinates,directionsUrl } from './maps';
import { emptySearch,filterProperties,placeTypes,placeType,type SearchFilters } from './property-search';
function toggle<T>(list:T[],value:T){return list.includes(value)?list.filter(v=>v!==value):[...list,value];}
export function Explorer(){
 const c=useEstate(),[f,setF]=useState<SearchFilters>({...emptySearch}),[mode,setMode]=useState<'cards'|'map'>('cards'),[sort,setSort]=useState('newest'),[selected,setSelected]=useState<string>(''),[detail,setDetail]=useState<Property|null>(null),[filtersOpen,setFiltersOpen]=useState(false),[photo,setPhoto]=useState(0),[sideTab,setSideTab]=useState('overview');
 const areas=[...new Set(c.data.properties.map(p=>p.locality))].sort();
 const amenities=[...new Set(['Parking','Garden','Balcony','Security','Lift',...c.data.properties.flatMap(p=>p.amenities)])].slice(0,18);
 const properties=useMemo(()=>filterProperties(c.data.properties,f,c.workspace.favorites).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='area'?b.area-a.area:Date.parse(b.created_at)-Date.parse(a.created_at)),[c.data.properties,c.workspace.favorites,f,sort]);
 const chosen=properties.find(p=>p.id===selected)||properties[0];const current=detail?.id===chosen?.id?detail:chosen;
 useEffect(()=>{if(!chosen){setDetail(null);return;}let live=true;setPhoto(0);setDetail(null);api('/properties/'+chosen.id).then(r=>{if(live)setDetail(r.property);}).catch(()=>{});return()=>{live=false;};},[chosen?.id,c.user?.id,c.data.properties]);
 function update<K extends keyof SearchFilters>(key:K,value:SearchFilters[K]){setF({...f,[key]:value});}
 const rangesInvalid=(f.priceMin&&f.priceMax&&+f.priceMin>+f.priceMax)||(f.areaMin&&f.areaMax&&+f.areaMin>+f.areaMax);
 async function save(p:Property){if(!c.user){c.signIn();return;}try{await api('/favorites/'+p.id,c.workspace.favorites.includes(p.id)?'DELETE':'POST');await c.refresh();}catch(e){c.notify((e as Error).message);}}
 function pick(p:Property){setSelected(p.id);setSideTab('overview');}
 return <div className="estate-explorer">
  <div className="explorer-intro"><div><span className="eyebrow"><span className="live-dot"/>{tr('BEAWAR, RAJASTHAN')}</span><h1>{tr('Find a place that feels like you.')}</h1><p>{tr('A new address. A fresh beginning. Explore your city with confidence.')}</p></div><Button onClick={c.newProperty}><Plus size={16}/>{tr('List property')}</Button></div>
  <div className="explorer-toolbar"><div className="segmented">{[['all','All'],['sale','Buy'],['rent','Rent']].map(([v,label])=><button key={v} className={f.purpose===v?'active':''} onClick={()=>update('purpose',v as SearchFilters['purpose'])}>{tr(label)}</button>)}</div><label className="explorer-search"><Search size={17}/><input aria-label={tr('Search properties')} placeholder={tr('Search a locality, address or property…')} value={f.query} onChange={e=>update('query',e.target.value)}/>{f.query&&<button aria-label={tr('Clear search')} onClick={()=>update('query','')}><X size={15}/></button>}</label><button className="btn outline filter-mobile" onClick={()=>setFiltersOpen(v=>!v)} aria-expanded={filtersOpen}><SlidersHorizontal size={16}/>{tr('Filters')}</button><div className="view-switch"><button aria-label={tr('Grid view')} aria-pressed={mode==='cards'} onClick={()=>setMode('cards')}><LayoutGrid size={17}/><span>{tr('Cards')}</span></button><button aria-label={tr('Map view')} aria-pressed={mode==='map'} onClick={()=>setMode('map')}><Map size={17}/><span>{tr('Map')}</span></button></div></div>
  <div className={'explorer-layout '+mode+'-layout'}>
   <aside className={'custom-filters '+(filtersOpen?'open':'')}><div className="filter-title"><strong><SlidersHorizontal size={16}/>{tr('Custom filter')}</strong><button onClick={()=>setF({...emptySearch})}>{tr('Clear all')}</button></div>
    <section><h3><MapPin size={15}/>{tr('Location')}</h3><div className="filter-checklist">{areas.map(a=><label key={a}><input type="checkbox" checked={f.localities.includes(a)} onChange={()=>update('localities',toggle(f.localities,a))}/>{tr(a)}<small>{c.data.properties.filter(p=>p.locality===a).length}</small></label>)}{!areas.length&&<p className="muted">{tr('Areas appear as listings are approved.')}</p>}</div></section>
    <section><h3>{tr('Price range')} <small>₹</small></h3><div className="filter-presets">{[[0,3000000,'Under ₹30 lakh'],[3000000,7500000,'₹30–75 lakh'],[7500000,0,'Above ₹75 lakh']].map(([min,max,label])=><button key={label} className={f.priceMin===String(min)&&f.priceMax===(max?String(max):'')?'active':''} onClick={()=>setF({...f,priceMin:String(min),priceMax:max?String(max):''})}>{tr(label)}</button>)}</div><div className="range-pair"><label><span>{tr('Min price')}</span><input aria-label={tr('Min price')} type="number" min="0" value={f.priceMin} onChange={e=>update('priceMin',e.target.value)} placeholder="₹ 0"/></label><label><span>{tr('Max price')}</span><input aria-label={tr('Max price')} type="number" min="0" value={f.priceMax} onChange={e=>update('priceMax',e.target.value)} placeholder={tr('Any')}/></label></div></section>
    <section><h3><Maximize2 size={15}/>{tr('Land area')}</h3><div className="range-pair"><label><span>{tr('Min sq ft')}</span><input aria-label={tr('Min sq ft')} type="number" min="0" value={f.areaMin} onChange={e=>update('areaMin',e.target.value)} placeholder="0"/></label><label><span>{tr('Max sq ft')}</span><input aria-label={tr('Max sq ft')} type="number" min="0" value={f.areaMax} onChange={e=>update('areaMax',e.target.value)} placeholder={tr('Any')}/></label></div></section>
    <section><h3><Building2 size={15}/>{tr('Type of place')}</h3><div className="filter-checklist">{placeTypes.map(type=><label key={type}><input type="checkbox" checked={f.types.includes(type)} onChange={()=>update('types',toggle(f.types,type))}/>{tr(type)}</label>)}</div></section>
    <section><h3>{tr('Amenities')}</h3><div className="amenity-filters">{amenities.map(a=><button key={a} aria-pressed={f.amenities.includes(a)} onClick={()=>update('amenities',toggle(f.amenities,a))}>{f.amenities.includes(a)&&<Check size={12}/>} {tr(a)}</button>)}</div></section>
    <section><h3>{tr('More preferences')}</h3><label className="bedroom-filter">{tr('Bedrooms')}<select value={f.bedrooms} onChange={e=>update('bedrooms',e.target.value)}><option value="">{tr('Any')}</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}+</option>)}</select></label><label className="check"><input type="checkbox" checked={f.available} onChange={e=>update('available',e.target.checked)}/>{tr('Available only')}</label><label className="check"><input type="checkbox" checked={f.saved} onChange={e=>{if(!c.user){c.signIn();return;}update('saved',e.target.checked);}}/>{tr('Saved properties only')}</label></section>
    <button className="btn filter-mobile" onClick={()=>setFiltersOpen(false)}>{tr('Show results')} ({properties.length})</button>
   </aside>
   <section className="explorer-results"><div className="results-heading"><div><strong>{properties.length} {tr('properties')}</strong><span>{tr('Your next chapter starts here')}</span></div><select aria-label={tr('Sort properties')} value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">{tr('Newest first')}</option><option value="low">{tr('Price: low to high')}</option><option value="high">{tr('Price: high to low')}</option><option value="area">{tr('Largest area')}</option></select></div>
    {rangesInvalid&&<p className="error">{tr('Minimum values must not exceed maximum values.')}</p>}
    {c.data.properties.some(p=>p.is_demo)&&<p className="compact-demo">{tr('Demo listings are examples. Add your real property and map pin to appear here after approval.')}</p>}
    {mode==='map'&&<div className="explorer-main-map"><PropertyMap properties={properties} selectedId={chosen?.id} onSelect={pick} height="100%"/><div className="map-count">{properties.filter(hasCoordinates).length} {tr('mapped properties')}</div></div>}
    {properties.length?<div className="explorer-cards">{properties.map(p=><article key={p.id} className={'explore-card '+(chosen?.id===p.id?'selected':'')}><button className="explore-image" onClick={()=>pick(p)} aria-label={tr('View {v0}',{v0:p.title})}><PropertyImage src={p.images[0]} alt={p.title}/><span className="place-badge">{tr(placeType(p))}</span>{p.is_demo&&<span className="sample-badge">{tr('Demo')}</span>}<span className="photo-count">{p.images.length} {tr('photos')}</span></button><button className={'explore-save '+(c.workspace.favorites.includes(p.id)?'saved':'')} aria-label={tr('Save {v0}',{v0:p.title})} onClick={()=>void save(p)}><Heart size={16} fill={c.workspace.favorites.includes(p.id)?'currentColor':'none'}/></button><div className="explore-copy"><button onClick={()=>pick(p)}><h3>{p.title}</h3></button><p><MapPin size={12}/>{p.locality}, {tr('Beawar')}</p><div className="explore-facts"><span><BedDouble size={13}/>{p.bedrooms}</span><span><Bath size={13}/>{p.bathrooms}</span><span><Maximize2 size={13}/>{p.area.toLocaleString(locale())} {tr('sq ft')}</span></div><div className="explore-price"><strong>{money(p.price)}{p.purpose==='rent'&&<small>{tr('/mo')}</small>}</strong><button onClick={()=>c.openProperty(p.id)} aria-label={tr('View details')}><ArrowUpRight size={18}/></button></div></div></article>)}</div>:<Empty title={tr('No properties match your search')} description={tr('Try broadening your filters or check back for new listings.')}><Button variant="outline" onClick={()=>setF({...emptySearch})}>{tr('Clear filters')}</Button></Empty>}
   </section>
   {current&&<aside className="property-spotlight"><div className="spotlight-gallery"><button onClick={()=>c.openProperty(current.id)} className="spotlight-main"><PropertyImage src={current.images[photo]||current.images[0]} alt={current.title}/></button><div>{current.images.slice(0,3).map((src,i)=><button key={src} onClick={()=>setPhoto(i)} className={i===photo?'active':''}><PropertyImage src={src} alt={tr('View photo {v0}',{v0:i+1})}/></button>)}</div><span>{current.images.length} {tr('photos')}</span></div><div className="spotlight-heading"><h2>{current.title}</h2><p><MapPin size={13}/>{current.locality}, {tr('Beawar')}</p><strong>{money(current.price)}<small>{current.purpose==='rent'?tr('/mo'):tr('For sale')}</small></strong></div><div className="spotlight-tabs">{['overview','photos','location'].map(v=><button key={v} aria-pressed={sideTab===v} onClick={()=>setSideTab(v)}>{tr({overview:'Overview',photos:'Photos',location:'Location'}[v])}</button>)}</div>
    {sideTab==='overview'&&<><p className="spotlight-description">{current.description}</p><div className="spotlight-facts"><span><BedDouble size={14}/>{current.bedrooms} {tr('beds')}</span><span><Bath size={14}/>{current.bathrooms} {tr('baths')}</span><span><Maximize2 size={14}/>{current.area.toLocaleString(locale())} {tr('sq ft')}</span>{current.amenities.slice(0,3).map(a=><span key={a}>{tr(a)}</span>)}</div><div className="spotlight-actions"><Button onClick={()=>c.openProperty(current.id)}>{tr('View all details')}<ChevronRight size={15}/></Button>{hasCoordinates(current)&&<a className="btn outline" href={directionsUrl(current)} target="_blank" rel="noreferrer"><Navigation size={14}/>{tr('Directions')}</a>}</div></>}
    {sideTab==='photos'&&<div className="spotlight-photo-grid">{current.images.map((src,i)=><button key={src} onClick={()=>{setPhoto(i);c.openProperty(current.id);}}><PropertyImage src={src} alt={tr('View photo {v0}',{v0:i+1})}/></button>)}</div>}
    {sideTab!=='photos'&&(hasCoordinates(current)?<PropertyMap value={current} height={215}/>:<div className="unmapped-note"><MapPin size={23}/><p>{tr('Exact map location has not been added to this older listing yet.')}</p></div>)}
    {sideTab==='location'&&<p className="muted">{current.address}</p>}
    {c.user&&<AssignedAgentCard agent={current.assigned_agent}/>}
   </aside>}
  </div>
 </div>;
}
