import { useEffect,useState } from 'react';
import { ArrowUpRight,Newspaper,Plus,RefreshCw,CalendarDays,Globe2,MapPin,Trash2 } from 'lucide-react';
import { useEstate } from './context';
import { api } from './api';
import { tr,locale } from './localization';
import { date,type News } from './types';
import { Button,Empty,Modal,Form } from './ui';
import { NewsForm } from './forms';
interface Article {id:string;title:string;url:string;source:string;publishedAt:string;scope:string}
interface Feed {articles:Article[];fetchedAt:string|null;stale:boolean;error:string;source:string}
export function NewsHub(){
 const c=useEstate(),[tab,setTab]=useState<'beawar'|'india'|'team'>('beawar'),[feed,setFeed]=useState<Feed|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[publish,setPublish]=useState(false),[selected,setSelected]=useState<News|null>(null),[remove,setRemove]=useState<News|null>(null);
 useEffect(()=>{if(tab==='team')return;let active=true;setFeed(null);const load=async()=>{setLoading(true);setError('');try{const r=await api<Feed>('/news-feed?scope='+tab);if(active)setFeed(r);}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},300000);return()=>{active=false;clearInterval(timer);};},[tab,retry]);
 return <div className="news-hub"><div className="news-hero"><div><span className="eyebrow">{tr('THE CITY EDIT')}</span><h1>{tr('Your city. In the know.')}</h1><p>{tr('Beawar headlines, India updates and announcements from your team.')}</p></div><div className="news-today"><CalendarDays size={24}/><span>{new Date().toLocaleDateString(locale(),{day:'numeric',month:'long',year:'numeric'})}</span><small>{tr('Beawar, Rajasthan')}</small></div></div><div className="news-controls"><div className="underlined-tabs">{[{id:'beawar',label:'Beawar news',Icon:MapPin},{id:'india',label:'India news',Icon:Globe2},{id:'team',label:'Team announcements',Icon:Newspaper}].map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id as typeof tab)}><t.Icon size={16}/>{tr(t.label)}</button>)}</div>{c.can('manage_content')&&<Button onClick={()=>setPublish(true)}><Plus size={15}/>{tr('Publish an update')}</Button>}</div>
 {tab!=='team'?<><div className="feed-status"><span><i className={'live-dot '+(feed?.stale?'stale':'')}/>{tr(feed?.stale?'Cached headlines':'Publisher headlines')}{feed?.fetchedAt&&<> · {tr('Updated')} {new Date(feed.fetchedAt).toLocaleTimeString(locale(),{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})} IST</>}</span><button className="btn ghost" disabled={loading} onClick={()=>setRetry(r=>r+1)}><RefreshCw size={14} className={loading?'spin':''}/>{tr('Refresh')}</button></div>
 {(error||feed?.error)&&<p className="notice" role="status">{tr(error||feed?.error)}</p>}
 {loading&&!feed?<div className="news-grid">{[1,2,3,4].map(n=><div key={n} className="skeleton news-skeleton"/>)}</div>:feed?.articles.length?<div className="news-grid">{feed.articles.map((a,i)=><a className={'live-news-card '+(i===0?'lead-story':'')} key={a.id} href={a.url} target="_blank" rel="noreferrer"><div className="news-card-kicker"><span>{tr(tab==='beawar'?'BEAWAR':'INDIA')}</span><time>{date(a.publishedAt)}</time></div><h2>{a.title}</h2><div className="news-card-source"><span><Newspaper size={15}/>{a.source}</span><ArrowUpRight size={20}/></div></a>)}</div>:<Empty title={tr('No headlines available right now')} description={tr('The feed may be temporarily unavailable or have no recent matching stories. Refresh later or read team announcements.')}/>}
 <p className="news-source-note">{tr('Headlines and publication dates come from external publishers. Open a story to read the original report. The feed refreshes automatically; no articles are invented.')}</p>
 </>:<>{c.data.news.length?<div className="news-grid">{c.data.news.map(n=><article className="team-news-card" key={n.id}><span className="eyebrow">{tr(n.category)}</span><h2>{n.title}</h2><p>{n.body.slice(0,180)}{n.body.length>180?'…':''}</p><div><time>{date(n.published_at)}</time><Button variant="ghost" onClick={()=>setSelected(n)}>{tr('Read update')}<ArrowUpRight size={15}/></Button>{c.can('manage_content')&&<button className="icon-btn" onClick={()=>setRemove(n)} aria-label={tr('Remove {v0}',{v0:n.title})}><Trash2 size={16}/></button>}</div></article>)}</div>:<Empty title={tr('City updates start here')} description={tr('Your team’s announcements will appear here. Live publisher news is available in the Beawar and India tabs.')}/>}</>}
 {publish&&<NewsForm onClose={()=>setPublish(false)}/>}{selected&&<Modal title={selected.title} onClose={()=>setSelected(null)}><span className="eyebrow">{tr(selected.category)} · {date(selected.published_at)}</span><p className="body-copy">{selected.body}</p>{selected.source_url&&<a className="btn outline" href={selected.source_url} target="_blank" rel="noreferrer">{tr('Original source')}<ArrowUpRight size={16}/></a>}</Modal>}
 {remove&&<Modal title={tr('Remove this update?')} onClose={()=>setRemove(null)}><p>{remove.title}</p><Form onSubmit={async()=>{await api('/news/'+remove.id,'DELETE');await c.refresh();setRemove(null);}}><div className="form-actions"><Button type="button" variant="outline" onClick={()=>setRemove(null)}>{tr('Cancel')}</Button><Button type="submit" variant="danger">{tr('Remove update')}</Button></div></Form></Modal>}
 </div>;
}
